name: Warpz0r
main: net.TheDgtl.Warpz0r.Warpz0r
author: Drakia
version: 1.1.0
commands:
  warp:
    description: Warp yourself to specified warp point
    usage: /<command> <name> - Warp to specified warp point
  warpto:
    description: Warp target player to specified warp point
    usage: /<command> <player> <name> - Warp target player to specified warp point
  listwarps:
    description: List all available warps
    usage: /<command> - List all available warps
  setwarp:
    description: Create a named warp at your current location
    usage: /<command> <name> - Create a named warp at your current location
  removewarp:
    description: Removes a named warp 
    usage: /<command> <name> - Remove a named warp
  home:
    description: Warp to your set home
    usage: /<command> - Warps you to your set home
  sethome:
    description: Sets your home
    usage: /<command> - Set your home
  wz:
    description: Set your compass direction
    usage: |
      /<command> compass - Set your compass to point to your home
      /<command> compass <warp> - Set your compass to point to <warp> 
      /<command> compass reset - Set your compass to point to spawn